// Code generated by protoc-gen-realmicro. DO NOT EDIT.
// source: bootstrap.proto

package bootstrap

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/realmicro/realmicro/client"
	server "github.com/realmicro/realmicro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for BootstrapService service

// Client API for BootstrapService service

type BootstrapService interface {
	// CreateAccount create a new account with username and password.
	//
	// @example {"account": {"username": "realmicro", "password": "realmicro111"}}
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...client.CallOption) (*CreateAccountResponse, error)
	// Login login to the system, return with login token.
	//
	// @example "username": "realmicro", "password": "realmicro111"}
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
}

type bootstrapService struct {
	c    client.Client
	name string
}

func NewBootstrapService(name string, c client.Client) BootstrapService {
	return &bootstrapService{
		c:    c,
		name: name,
	}
}

func (c *bootstrapService) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...client.CallOption) (*CreateAccountResponse, error) {
	req := c.c.NewRequest(c.name, "BootstrapService.CreateAccount", in)
	out := new(CreateAccountResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "BootstrapService.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BootstrapService service

type BootstrapServiceHandler interface {
	// CreateAccount create a new account with username and password.
	//
	// @example {"account": {"username": "realmicro", "password": "realmicro111"}}
	CreateAccount(context.Context, *CreateAccountRequest, *CreateAccountResponse) error
	// Login login to the system, return with login token.
	//
	// @example "username": "realmicro", "password": "realmicro111"}
	Login(context.Context, *LoginRequest, *LoginResponse) error
}

func RegisterBootstrapServiceHandler(s server.Server, hdlr BootstrapServiceHandler, opts ...server.HandlerOption) error {
	type bootstrapService interface {
		CreateAccount(ctx context.Context, in *CreateAccountRequest, out *CreateAccountResponse) error
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
	}
	type BootstrapService struct {
		bootstrapService
	}
	h := &bootstrapServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BootstrapService{h}, opts...))
}

type bootstrapServiceHandler struct {
	BootstrapServiceHandler
}

func (h *bootstrapServiceHandler) CreateAccount(ctx context.Context, in *CreateAccountRequest, out *CreateAccountResponse) error {
	return h.BootstrapServiceHandler.CreateAccount(ctx, in, out)
}

func (h *bootstrapServiceHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.BootstrapServiceHandler.Login(ctx, in, out)
}
