// Code generated by protoc-gen-realmicro. DO NOT EDIT.
// source: envelope.proto

package protorpc

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
